version: "3.3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api
        env_file:
            - .env
        environment:
            - GO111MODULE=on
            - CGO_ENABLED=0
            - GOOS=linux            
        ports:
            - 8000:8000
        depends_on:
            - mongo
        networks:
            - servicesnetwork                          
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        networks:
            - servicesnetwork              
    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        networks:
            - servicesnetwork            
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
networks:
    servicesnetwork:
        driver: bridge